version: '3.9'

services:
  web:
    restart: unless-stopped
    image: idebackend:0.0.1
    volumes:
      - ./packages/api/src:/usr/src/app/packages/api/src
      - ./projects:/usr/src/app/projects
    command: npm run dev
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: devserver

